
[[dependencies]]
  branch = "master"
  name = "github.com/BurntSushi/toml"

[[dependencies]]
  branch = "master"
  name = "github.com/Sirupsen/logrus"

[[dependencies]]
  name = "github.com/containers/virtcontainers"
  revision = "13f8a29844ae916e3da6ba66a22df4f5ee01826c"

[[dependencies]]
  name = "github.com/opencontainers/runtime-spec"
  version = "v1.0.0-rc5"

[[dependencies]]
  branch = "master"
  name = "github.com/urfave/cli"
